### ISSUE TITLE
Profile Manifest with a pfm_type: array does not allow you to click Add button in GUI

### ISSUE THREAD

**Issue by bp88** [erikberglund/ProfileCreator#101]
See the animated gif as an example. For example, in the Firefox payload, go to the  Authentication > SPNEGO section and try to click on the Add (+) button multiple times.  In this case, it looks like whether intentional or not, you cannot add another entry until the empty entry has been filled.

There are two options here: 1) the Add (+) gradient button should either be greyed out to indicate that an entry needs to be filled or 2) the Add (+) gradient button remains active and should continue to allow the user to add empty entries.

I believe the first option is preferable in this case. Here is a gif showing what I'm referring to:

![profilemanifests1](https://user-images.githubusercontent.com/5908234/50460114-b920c400-0940-11e9-9120-9881fb38838d.gif)

In case gif didn't upload correctly: https://imgur.com/a/zCI2mrS

**Comment by erikberglund** [comment]
This was a separate issue and it's fixed for the next release

**Comment by apizz** [comment]
Fixed in 0.2.5 release
