### ISSUE TITLE
Bug: Array of boolean items has no UI

### ISSUE THREAD

**Issue by smaddock** [erikberglund/ProfileCreator#104]
Can't set values in an array of booleans.

![screen shot 2018-12-28 at 2 42 40 pm](https://user-images.githubusercontent.com/524425/50528988-ea1f0700-0aae-11e9-8d7a-29336693522c.png)

**Comment by erikberglund** [comment]
This is fixed in the next version.

**Comment by apizz** [comment]
Fixed in 0.2.5 release
