### ISSUE TITLE
New OneDrive values available

### ISSUE THREAD

**Issue by patgmac** [erikberglund/ProfileCreator#112]
https://docs.microsoft.com/en-us/OneDrive/files-on-demand-mac

**Comment by apizz** [comment]
@patgmac Added commit in [my fork](https://github.com/apizz/ProfileManifests) via [this commit](https://github.com/erikberglund/ProfileManifests/pull/17/commits/a6eb02d9cb999da776a86d8ff3a023da10c440f0).

You can use it until it gets merged.  I know @erikberglund has been busy

**Comment by apizz** [comment]
@patgmac the new keys are now available per https://github.com/erikberglund/ProfileManifests/pull/30.

If this resolves this issue, please close it when you are able.
