### ISSUE TITLE
Deprecated text hidden when pfm_title is used

### ISSUE THREAD

**Issue by apizz** [erikberglund/ProfileCreator#118]
When adding a preference that is deprecated, in my case `pfm_ios_deprecated`, when a `pfm_title` is defined the red deprecated text that usually appears does not.

When the title is selected to reveal the `pfm_name` only then is the deprecated text visible.

Example below is from Restrictions (iOS) manifest I'm working on.

![screen shot 2019-02-12 at 2 13 58 pm](https://user-images.githubusercontent.com/11789931/52661661-815de380-2ed0-11e9-9da8-e3ad3fa55e22.png)
![screen shot 2019-02-12 at 2 14 01 pm](https://user-images.githubusercontent.com/11789931/52661671-8458d400-2ed0-11e9-8f92-6c7278080361.png)

**Comment by erikberglund** [comment]
Ok, this is probably an issue with the textfields interacting. I should probably make deprecated text part of the title but as an attributed text to avoid this issue. I will look into it.

**Comment by apizz** [comment]
Looks resolved in beta build of 0.2.5

**Comment by apizz** [comment]
Fixed in 0.2.5 release
