### ISSUE TITLE
Option to export as plist

### ISSUE THREAD

**Issue by ahrenstein** [erikberglund/ProfileCreator#123]
It would be really useful to be able to export some payloads as plists (Chrome and NoMAD are good examples) so that they can be uploaded to Jamf in a way that allows updating the settings without having to delete and recreate the entire profile.

**Comment by apizz** [comment]
I agree that that would be helpful, @ahrenstein 

What's your process for doing this now?  How I've been doing this is building the profile payload and switching to XML view and then copying and pasting into a PLIST template.

**Comment by apizz** [comment]
I know that this blog post https://erikberglund.github.io/2018/Profile_Creator_Beta_1/ mentions including adding support for MDM APIs so that profiles can be directly uploaded, and hopefully updated as well

**Comment by ahrenstein** [comment]
Currently I just upload the profiles entirely after signing, and dealing with the whole "delete then re-upload" thing.

Having MDM APIs used to upload profiles would be amazing!

**Comment by erikberglund** [comment]
When exporting a profile, if you change the payload format to XML its creating a profile with the old mcx style content. You dont have to sign that, just upload it to jamf and you will get a ”custom payload” in the gui. So that feature already exists. And remember, the sig ung is only required for payloads that jamf has a gui for that they will insett their own settings to even if you dont want. But for third party profiles, or Custom Payloads that does not matter as jamf will not add anything extra to those.

I should add a note about this in the export window probably

**Comment by ahrenstein** [comment]
I'll have to give that a shot. I mostly was aiming to customize payloads Jamf is aware of (eg: Configure Filevault Key Escrow without Firewall) but I wanted to avoid having to sign the profiles and upload them since minor edits are deleting and replacing the whole profile.

**Comment by erikberglund** [comment]
![skarmavbild 2019-03-01 kl 20 32 34](https://user-images.githubusercontent.com/1296345/53665114-cae95500-3c6a-11e9-8524-00d5d8296f8a.png)
Here is an image showing where to change the format of the payload contents. This is only available for third party profiles, as the Apple profiles has to have their correct PayloadType in the profile.

**Comment by erikberglund** [comment]
Also, when you say you want to export it "as plist", what exactly are you looking for? As a profile is already a plist. Is there some other format you want the settings in?

**Comment by ahrenstein** [comment]
My main goal was to import existing profile options as custom payloads so I can update profiles in Jamf that it has a UI for without having to sign them and without having to use the UI which would force configuring extra options.

**Comment by apizz** [comment]
@ahrenstein If IIRC (and I haven't tried or tested this myself), if you only want to manage only certain preferences which is a part of an Apple payload (ex. Login Window) without configuring a lot more that you have to use the **Custom Settings** payload

**Comment by erikberglund** [comment]
I dont know about jamf enough to help here, but you want only some keys for an Apple payload but not the default extra keys that jamf adds, but you want to not sign it so you can Edit that in the jamf gui.

The thing i have a hard time seeing is to put an Apple payload in a custom profile wrapping. Most Apple payloads are not just preferences keys but the plugin that installed the profile actually does something with the configuration, so puttningen that as a custom profile would make the profile not work.

If you can show me an example plist output that you would like for a payload that works, pleas put that here so i can look at what it is you want more specifically.

**Comment by ahrenstein** [comment]
It may not be possible with the default OS payloads. I could not get it to work. I think we can close this request as "won't do"

Thanks for looking in to it though.

**Comment by erikberglund** [comment]
You should file an issue with jamf so they stop adding extra keys to uploaded profiles.
