### ISSUE TITLE
Missing AutomaticallyInstallMacOSUpdates setting in SoftwareUpdate payload 

### ISSUE THREAD

**Issue by patgmac** [erikberglund/ProfileCreator#125]
I don't see the following setting available in the SoftwareUpdate payload (or anywhere else). 

com.apple.SoftwareUpdate.plist AutomaticallyInstallMacOSUpdates -bool true

This is what sets the "Install macOS Updates" to enabled in the Software Updates pane.

**Comment by erikberglund** [comment]
Have you tried this setting in a profile recently?

According to rich, in this article: https://derflounder.wordpress.com/2018/12/28/enabling-automatic-macos-software-updates-for-os-x-yosemite-through-macos-mojave/ he says: 

> Unfortunately, it is not yet possible to set these automatic update settings using a profile. The com.apple.commerce preference domain can’t be managed by a profile and the AutomaticallyInstallMacOSUpdates setting in the com.apple.SoftwareUpdate preference domain should be manageable with a profile, but for unknown reasons, it can’t be.

If it works, I will add it. But it might be os-specific if it didn't work when rich tried, so it would require some testing to get the supported os version down.

**Comment by patgmac** [comment]
You are correct. These settings are inconsistent in a profile. Oh well, using a script.

**Comment by erikberglund** [comment]
It might also be a bug, who knows. I will absolutely add it if it works somewhere, maybe with a note of caution.
