### ISSUE TITLE
Keep repeat payload focus when switching between GUI & XML views

### ISSUE THREAD

**Issue by apizz** [erikberglund/ProfileCreator#127]
For payloads that support multiple payloads of the same type (ex. Wi-Fi), additional payload tabs appear.  However, when switching between GUI & XML views, the *first* payload is always selected.  Would like PC to keep the selected payload in focus when switching between GUI & XML views.

A description of what happens currently:

1. With multiple payloads created, select any payload except the first in the GUI builder.
![Screenshot 2019-03-10 14 08 20](https://user-images.githubusercontent.com/11789931/54089327-41a6e200-433e-11e9-91da-fdb1664da292.png)
2. Click the XML view button.
3. XML view switches back to the first payload, rather than displaying the selected payload XML.
![Screenshot 2019-03-10 14 08 50](https://user-images.githubusercontent.com/11789931/54089335-54211b80-433e-11e9-94ef-35088c42998e.png)
4. Select the desired payload in XML view.
5. Click the GUI builder button to switch back.
6. Once again, the first payload is selected.

**Comment by erikberglund** [comment]
Fixed for the next release.

**Comment by apizz** [comment]
Looks like this is actually a duplicate of #59

**Comment by apizz** [comment]
Fixed in 0.2.5 release
