### ISSUE TITLE
Need ability to set past date & time for `pfm_type` date

### ISSUE THREAD

**Issue by apizz** [erikberglund/ProfileCreator#129]
I started working on a manifest for com.apple.touristd, which handles the "New to Mac" and "What's New to Mac" notifications and in order to suppress these notifications I need to be able to set a date and time in the past.  However, it appears with the current implementation it's not possible to set a historic date & time for this purpose.  This would be a helpful addition.

**Comment by erikberglund** [comment]
Fixed for the next release.

**Comment by apizz** [comment]
Added in 0.2.5 release
