### ISSUE TITLE
Feature Request: WiFi Preferred Networks

### ISSUE THREAD

**Issue by jekastner** [erikberglund/ProfileCreator#130]
Erik, 

Thanks for the recent release of ProfileCreator it addressed some of the buggy issue with the WiFi Payload. It works great. But, I would love to see an option to add a specific SSID to be always at the Top of the Preferred Network order list. 

Included a print screen shot of that I am referring. 

![Screen Shot 2019-03-19 at 12 16 34 PM](https://user-images.githubusercontent.com/43783356/54627168-ddbca180-4a40-11e9-88fb-3e79b3e04662.png)

**Comment by kevinmcox** [comment]
Jason, is that something configurable via a profile? I don't see any mention of that option in Apple's profile reference, but if it exists it would be good to include.

**Comment by jekastner** [comment]
Kevin, 

It can be scripted out but I am trying to keep scripts at a minimum and prefer using profiles. Like you I cannot find a reference for it .

**Comment by erikberglund** [comment]
@jekastner We are unfortunately bound by what Apple lets us configure with a payload. So if Apple hasn't made a plugin that can configure a certain setting when set in a profile, there is nothing anyone can do to accomplish this I'm afraid.

I suggest you instead send this as a feature request to Apple.

Apple has opened up the "custom" profile option, but what that does is only configuring static values for a preference domain, like in a preference plist file. This setting here is not just a setting in a preference file so it cannot be managed in a satisfactory way using that custom option, and that is all we have.

If you really wanted you could write your own plugin or app that listens for profile installations (i have done that once) and act for things like this. But that is quite a big investment for things that are scriptable. But if you really need to only rely on profiles, that would be my suggestion in this case.

But yes, please file an issue with Apple so they add this feature to their supported keys.

I'm going to close this issue as there is nothing we can do.

If you or anyone else know of a way to add this through a profile, please let me know and I'll gladly add it to the application.
