### ISSUE TITLE
How to use identity payload

### ISSUE THREAD

**Issue by ofirgalcon** [erikberglund/ProfileCreator#133]
With Apple PM you can use identity to prompt users to enter some details which are stored in variables you can use for other payloads within same profile.

How can I use this in profilecreator?

**Comment by erikberglund** [comment]
The variables are used by the MDM that installs the profile. Variables cannot be used when manually installing a profile. ProfileCreator only creates profiles so it can configure the variables your MDM needs as well, but there currently is no support for showing what variables are available per MDM etc. which is a feature I would like to have some day.
