### ISSUE TITLE
New Feature Request - Keychain Management

### ISSUE THREAD

**Issue by jekastner** [erikberglund/ProfileCreator#140]
Is it possible for Profile Creator to have a section on Keychain Management?

Our Macs are connected to Active Directory, whenever we reset the AD password users get that "Create New or Update Keychain prompt."

Is there a way for Profile Creator to auto create new keychains after an Active Directory password rest?

**Comment by apizz** [comment]
@jekastner the Keychain issues you're experiencing cannot be resolved by ProfileCreator. 

You would want to look at something like NoMAD to help with this.  I know that a related project - NoMADLogin - can also help deal with this by checking if the supplied password at the loginwindow unlocks the keychain, and if not can optionally create a new keychain automatically.

**Comment by erikberglund** [comment]
@jekastner Yes, as @apizz said, ProfileCreator only creates profiles, so if Apple doesn't have a profile plugin och a setting for that that we could put in a profile, then ProfileCreator can't help with that.

I would also suggest looking at NoMAD. It's free for the AD version and it's a very good tool.
