### ISSUE TITLE
Add support for pfm_exclude and pfm_conditionals to reference preferences from other manifests

### ISSUE THREAD

**Issue by apizz** [erikberglund/ProfileCreator#148]
Expand on the support added for `pfm_value_copy` and `pfm_default_copy` in 0.2.5 to reference preferences from other manifests via the format `<manifest>@<preference_pfm_name>`

As one example, `forceClassroomUnpromptedScreenObservation` in the macOS & iOS Restrictions manifests is dependent on `ScreenObservationPermissionModificationAllowed` from the Education payload being set to `true`.

**Comment by erikberglund** [comment]
Yes, that should be the unified method. But, there currently is a way to do this already with conditionals. Look at this example: 

https://github.com/erikberglund/ProfileManifests/blob/0a940d6ab1dd5fc50d0648a80319c7a427bcdc22/Manifests/ManifestsApple/com.apple.finder.plist#L173-L193

And, I originally had the @ format, but I now have forgotten why I changed that to use a key instead.. There was a reason..

But for now, you can get the result you are looking for using `pfm_domain` as in the example above.

If not, update here.

**Comment by apizz** [comment]
@erikberglund That makes a lot of sense.  I'll give that a try and confirm.

If it works as expected, I'll add this to the wiki

**Comment by apizz** [comment]
OK, @erikberglund. Confirmed that works as expected using `pfm_domain` and `pfm_target`.  The only thing is that the exclusion rule won't indicate the payload that the preference refers to.

![Screen Shot 2019-04-10 at 11 15 56 AM](https://user-images.githubusercontent.com/11789931/55891143-076d7200-5b82-11e9-9419-f703e89f8e80.png)
