### ISSUE TITLE
Uploaded Fonts & Certs can't easily be removed once uploaded

### ISSUE THREAD

**Issue by apizz** [erikberglund/ProfileCreator#156]
In both the Apple Fonts & Certs payload, once you have uploaded a font or cert you cannot remove it.  As a result, you currently have to do one of the following:

- Delete the saved profile and create a new one
- Quit ProfileCreator (not saving the profile) and rebuild
- Add a new Font and/or Cert payload (create a new tab) and remove the one with the font or cert added to remove it

I think a remove button here would be helpful.

**Comment by erikberglund** [comment]
Yes, added it for the next version.

**Comment by apizz** [comment]
Confirmed resolved in v0.3.0 release. Thanks!
