### ISSUE TITLE
Minor UI improvements

### ISSUE THREAD

**Issue by wjk** [erikberglund/ProfileCreator#159]
I noticed the following minor UI issues in the app (beta 0.2.5-12):

* The View ➪ Hide Toolbar menu command is usable; IMO it should be removed (along with the always-disabled View ➪ Customize Toolbar command) because having the toolbar visible at all times is important to correctly use the app.
* When you click-and-hold on the Add Payloads or Keys menu, then select Add Payload Key from the menu, an empty sheet appears. If this feature is not yet fully implemented (which I don't think it is), this command should either display an error message or do nothing (as with the Add Payload command).

Keep up the good work!

**Comment by erikberglund** [comment]
Thank you, yes the toolbar menu item should be hidden. I've hidden that for the next update.

And I thought I had hidden the add payload key as I never connected the ui and that sheet as there were still some issues I didn't have time to finish. I'll hide those too, as next update is done just finishing some manifests. So it will ot add that either.

**Comment by erikberglund** [comment]
There are a few more of these types of issues, I should look at those. If you find anything else, please don't be afraid of opening more issues.
