### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by ecanault** [erikberglund/ProfileCreator#160]
Hi,

I can't find the download links from here https://github.com/erikberglund/ProfileCreator/releases

What am I missing :-/ ?

Regards,
Emmanuel

**Comment by ecanault** [comment]
OK, found it in the #profilecreator channel in Mac Admins Slack.

**Comment by erikberglund** [comment]
I have heard other with this issue, I will add links to the readme on the front-page as well so it will be easier to find.

**Comment by ecanault** [comment]
Hi Erik,

Thanks for that !

Regards,
Emmanuel

--
[signature_605141433]<https://www.netopie.fr/>

Emmanuel CANAULT - Ing?nieur Syst?me
? Apple Consultant Network | ACTC | ACSP
Jamf  Integrator | CCE | CCA | CCT
[signature_600144889]  ecanault@netopie.fr<mailto:ecanault@netopie.fr> / support@netopie.fr<mailto:support@netopie.fr>
[signature_923607423]  +33 1 76 21 02 50<tel:+33%201%2076%2021%2002%2050>?
[signature_1874000749]  88, Boulevard Gallieni 92130 Issy-Les-Moulineaux<x-apple-data-detectors://4>



N'imprimez ce courriel que si n?cessaire


Le 15 mai 2019 ? 14:50, Erik Berglund <notifications@github.com<mailto:notifications@github.com>> a ?crit :


I have heard other with this issue, I will add links to the readme on the front-page as well so it will be easier to find.

-
