### ISSUE TITLE
Please add support for macOSLAPS

### ISSUE THREAD

**Issue by yon2004** [erikberglund/ProfileCreator#164]
The ability to create a profile for macOSLAPS would be helpfull. Documentation is avalible here: https://github.com/joshua-d-miller/macOSLAPS

**Comment by erikberglund** [comment]
I just added this to the manifest repo.

It should be available in ProfileCreator at next launch, or if you have not enabled automatic manifest updates you can go into ProfileCreator -> Preferences -> Payloads and click "Check Now", then "Update".

![Screenshot 2019-05-29 at 10 13 26](https://user-images.githubusercontent.com/1296345/58540818-6a7e9b00-81fa-11e9-9129-221bbed4cf65.png)
