### ISSUE TITLE
Mark sensitive fields, like passwords, to identify how they should be stored.

### ISSUE THREAD

**Issue by erikberglund** [erikberglund/ProfileCreator#31]
Currently all settings are stored in the plain text plist template format.

This is not ideal for profiles containing payload keys with sensitive information like preshared keys, passwords etc.

These fields should be marked in the framework, and then display a UI warning that they will be saved in plain text.

Later, when an application keychain is implemented, this marking will be used to determine what settings should be stored there.

**Comment by krispayne** [comment]
Would this also apply to the password field in the "With Authorization" profile removal, or should this be opened as a new issue?

![screen shot 2016-10-24 at 12 30 34 pm](https://cloud.githubusercontent.com/assets/70580/19660692/af86b6ce-99e5-11e6-8007-c708a8868116.png)

**Comment by erikberglund** [comment]
Yes. that would apply there too. It should be noted both that this will be visible in the profile when exported as mobileconfig (and not encrypted). But also, at least until fixed, that it's saved in plain text on disk.

**Comment by erikberglund** [comment]
I've added this now, using system icons as placeholders. Currently only "required" and "sensitive" fields are show. The information is added to the tooltip for the icon. This will be expanded further at a later time to include better icons and more information possibly.

The tooltip is additive so if there are multiple warnings or errors, all will be included.

There are more things to implement for this feature. When exporting, the custom accessory view should display a warning if any of these "sensitive" fields are included in the profile.

The warning for sensitive data will only be shown if there is a value in the field, else that warning is not shown so it doesn't clutter the UI, and also makes it mor noticeable that an icon appears when you start typing in such a field.

Anyway, here is a screenshot of the "Required" icon at the top, and the "Warning" icon for sensitive data below.

![screen shot 2016-11-06 at 18 03 37](https://cloud.githubusercontent.com/assets/1296345/20039878/a2038592-a44c-11e6-9a9a-f73c3c7ac2c8.png)
