### ISSUE TITLE
Clicking "Save" has no visible action

### ISSUE THREAD

**Issue by krispayne** [erikberglund/ProfileCreator#42]
When you click save on the profile creation window, the profile is saved in the background but there's no visible action taken (i.e. window close)

**Comment by erikberglund** [comment]
Yeah, that is a good catch. Also, the Cmd-S shortcut should be able to be used to save, haven't added that as an issue i think.

I didn't think of it as save & close when adding that, but it should show something that it was successful. Also, it might be more useful with a save & close. I'll test and see how that works, or if there is a setting or another way to get both behaviours if needed.

**Comment by erikberglund** [comment]
Hi. After thinking about this, I've decided to remove the save button entirely and instead connect the File -> Save… menu item to the save feature.

The idea is that each profile is like document, think pages etc.. and it should be possible to try settings without committing to them, therefore not saving all changes. And the save button is not a standard interface anymore and instead it will ask when closing, or the user can choose save from the file menu or Cmd-S to save the current state and keep the window open.
