### ISSUE TITLE
Banner settings not saving value

### ISSUE THREAD

**Issue by timelost11** [erikberglund/ProfileCreator#44]
When attempting to add the banner message to the login window payload, the values entered are not being saved. It seems to be removing the values whenever another option is selected. I also noticed that no values are being moved over to the xml view.

**Comment by erikberglund** [comment]
Thank you, and you are correct. That is a TextView and I think it's the only one in the app atm, and I have not tested it after I made some internal changes some time ago.

Have fixed it now for the next update.

Do you have an example of an enabled key that doesn't show up in the xml view? And are you on 10.12 or 10.13?

**Comment by timelost11** [comment]
Sorry, the key shows up, but the string remains empty.

I am currently running this on the 10.14 beta.

**Comment by erikberglund** [comment]
Ok, thank you. I have reproduced and fixed this. An update will probably be available within a week, maybe shorter.

**Comment by erikberglund** [comment]
This is fixed, please open a new issue if the problem returns
