### ISSUE TITLE
Tab highlighting under Applications

### ISSUE THREAD

**Issue by kevinmcox** [erikberglund/ProfileCreator#45]
I noticed that when switching through the tabs under the Applications (Munki, NoMAD) that "General" remains depressed/highlighted even when other tabs are selected. In the case of this screenshot I have the "Log" tab selected. This is running on macOS 10.12.6.

![Munki options](https://user-images.githubusercontent.com/25358601/42109914-f05e5ce0-7ba4-11e8-8ba1-30a44fc2871e.png)

**Comment by erikberglund** [comment]
Took some wider testing but I found the issue, it was an index out of bounds error, but the 10.13 API caught that gracefully and the 10.6+ API crashed. So, good that it got fixed. Added the fix to the next release.

**Comment by kevinmcox** [comment]
Looks good in 0.1 Beta 2!
