### ISSUE TITLE
Prompts for keychain access as soon as app is launched

### ISSUE THREAD

**Issue by rickheil** [erikberglund/ProfileCreator#49]
The prompt for keychain access comes out of nowhere and may confuse users who don't connect the "need keychain access to sign things" with the prompt right away. It should only pop up when actually trying to sign a profile for the first time, or when selecting the signing certificate in preferences. Perhaps when setting your certificate in preferences, the UI could be a button to load available certificates that triggers the prompt the first time (or successive times if the user doesn't click Always Allow)?

**Comment by erikberglund** [comment]
Yeah, thanks for reminding me about this. It should definitely be the first time you select a certificate for signing. I will put this first on the list to fix for the next version.

**Comment by erikberglund** [comment]
Hello again. Today I have tried to recreate this behavior but I have not been able to do it. I have downloaded the latest release on a fresh 10.12 and 10.13 VM and launched it for the first time, but I have never gotten a keychain prompt. I've tried on another user Mac that never used ProfileCreator and that didn't show me a prompt either.

I've tried locking the keychain to see if that might be the issue, but that didn't give me anything either. So right now I can't recreate this issue without some more information.

Did this go away after you gave your password?
Do you remember or have a screenshot of the prompt?
Can you recreate this?
Do you have multiple keychains, other than Login, iCloud and System?
Do you have any special settings in the authorization database for keychain access?

And finally, do you have a theory of what it could be?

Do you have another machine that ProfileCreator has been used on to verify this and if it appears take a screenshot?

**Comment by sphen13** [comment]
I have not seen this issue either. I was prompted to always allow keychain access when I signed my first profile and good after that. Latest build.

On Jul 21, 2018, at 9:39 AM, Erik Berglund <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello again. Today I have tried to recreate this behavior but I have not been able to do it. I have downloaded the latest release on a fresh 10.12 and 10.13 VM and launched it for the first time, but I have never gotten a keychain prompt. I've tried on another user Mac that never used ProfileCreator and that didn't show me a prompt either.

I've tried locking the keychain to see if that might be the issue, but that didn't give me anything either. So right now I can't recreate this issue without some more information.

Did this go away after you gave your password?
Do you remember or have a screenshot of the prompt?
Can you recreate this?
Do you have multiple keychains, other than Login, iCloud and System?
Do you have any special settings in the authorization database for keychain access?

And finally, do you have a theory of what it could be?

Do you have another machine that ProfileCreator has been used on to verify this and if it appears take a screenshot?

**Comment by erikberglund** [comment]
@sphen13 Thanks for your info, yes that is the expected behaviour. Good to hear that not everyone seems affected by this.

**Comment by rickheil** [comment]
I may have been using an older build then... will check when I get to work on Monday.

**Comment by erikberglund** [comment]
There might be reasons this is happening, so if you still can reproduce it might be helpful. But when implementing this I've followed many examples from Apple and have not seen any extra steps to preauthorize or seen any checks where it would present a dialogue. So it might be something special with the keychain you have.

**Comment by rickheil** [comment]
I was opening the first beta build... d'oh! Sorry for the added noise here.
