### ISSUE TITLE
pfm_value_placeholder only supports string

### ISSUE THREAD

**Issue by clburlison** [erikberglund/ProfileCreator#50]
When attempting to create a manifest with a placeholder value as an integer ProfileCreator will use the value of 1 instead of my placeholder. This works with string but `pfm_value_placeholder` needs to match `pfm_type` from my tests.

Pretty low priority issue but it can be replicated with the following using 0.1 beta3 of ProfileCreator.

```xml
<dict>
    <key>pfm_app_min</key>
    <string>3.0.0</string>
    <key>pfm_default</key>
    <true/>
    <key>pfm_description</key>
    <string>Change how often the Microsoft AutoUpdate daemon will look for updates. The default is 720 minutes (12 hrs). By reducing this value MAU will look for updates sooner.</string>
    <key>pfm_name</key>
    <string>UpdateCheckFrequency</string>
    <key>pfm_title</key>
    <string>Update check frequency</string>
    <key>pfm_type</key>
    <string>integer</string>
    <key>pfm_value_placeholder</key>
    <integer>720</integer>
</dict>
```

![screen shot 2018-07-19 at 9 46 20 am](https://user-images.githubusercontent.com/2831320/42949972-9ea42472-8b38-11e8-9907-045906ab4096.png)

**Comment by erikberglund** [comment]
This was a typo in the manifest, an incorrectly included `<key>pfm_default</key>` that returned the 1 instead of the entered value.
