### ISSUE TITLE
Feature Idea: drag and drop support for firewall profiles

### ISSUE THREAD

**Issue by rickheil** [erikberglund/ProfileCreator#51]
In the firewall profile, it would be amazing if one could drag and drop an app bundle onto the "Applications" section and have ProfileCreator automatically grab the bundle ID and name from Info.plist (CFBundleIdentifier and CFBundleDisplayName). This would help speed up creating of firewall profiles where app publishers have a different TLD or have versioning in their bundle IDs.

**Comment by erikberglund** [comment]
This is now in the application.
