### ISSUE TITLE
Automatic Proxy Configuration produces error

### ISSUE THREAD

**Issue by jamescapen** [erikberglund/ProfileCreator#52]
Tried creating a profile where the only settings are to enable automatic proxy configuration and receive the error:

```
Invalid value for key: ProxyAutoConfigEnable in payload domain: com.apple.SystemConfiguration of type:appleManifest

Value: https://example.com/pacfile.pac

Verify you have entered a correct value.
```

It looks like the `Automatic Proxy Configuration URL` setting is using the same key as `Enable Automatic Proxy Configuration` i.e. `ProxyAutoConfigEnable`

Not sure what the correct key is, `ProxyAutoConfigURLString`?

**Comment by erikberglund** [comment]
Thank you, yes you are correct. That key was duplicated, and incorrect. I've fixed this and uploaded it to the manifest repo. If you have beta 3 you can go into Preferences > Payloads and click on "Update Now", then "Update" and you should get the new manifest and be able to build your profile correctly.
