### ISSUE TITLE
VPN Settings?

### ISSUE THREAD

**Issue by dustinjlandgraf** [erikberglund/ProfileCreator#54]
I don't see anywhere to configure a VPN payload. Is that missing for any particular reason?

**Comment by kevinmcox** [comment]
ProfileCreator is still under very early (but active) development. Payloads are being added slowly but Erik has been prioritizing requests.

**Comment by dustinjlandgraf** [comment]
Thanks @kevinmcox! I honestly just figured it was there and I wasn't seeing it, so I figured I'd ask for a sanity check. I'm really liking where this project is going!
