### ISSUE TITLE
Some specific description strings don't calculate the required textfield height correctly.

### ISSUE THREAD

**Issue by erikberglund** [erikberglund/ProfileCreator#57]
Sometimes the calculation of the description textfield height is off, and the end of the description get hidden. 

The code that calculates the textfield required size needs to be updated.

Example:

Passcode -> "Maximum grace period for device lock"

**Comment by erikberglund** [comment]
That is the same issue, and this is fixed for the next version

**Comment by apizz** [comment]
Fixed in 0.2.5 release
