### ISSUE TITLE
FR: add setting for storing the library at a specific path

### ISSUE THREAD

**Issue by nathanperkins** [erikberglund/ProfileCreator#60]
I'd like to put our profiles library in a specific path so they can be a part of our organization's private macOS git repo, for better versioning and sharing.

**Comment by erikberglund** [comment]
Thanks, and yes that is a needed feature that I too have added to the list of things I need to add. We would use that too.

My thinking has been to allow the whole save location to relocate, and an option per-group in the main window. But that comes with other challenges, so at first an option to change the base location for the profiles and for the group settings.

I will add it to things to do for the next update, I try to prioritize requests.

**Comment by nathanperkins** [comment]
Looks like it works! Big improvement for our team :)

If I might suggest, you could make it so the Groups folder is included, so that the organization of the profiles can easily be put into version control as well.

**Comment by erikberglund** [comment]
Yes I agree and I plan to add a second setting for groups, but wanted to get the fix out as Quick as possible for the breaking things so i pushed that for the next update.

**Comment by erikberglund** [comment]
This was fixed in Beta 6. Please open a new issue if there are issues with this. The option for changing the group save files will be added to Beta 7.
