### ISSUE TITLE
SoftwareRepoURL is shown as "required" for Munki payload

### ISSUE THREAD

**Issue by nathanperkins** [erikberglund/ProfileCreator#61]
The SoftwareRepoURL field is marked as required. I don't think this field is really required, as munki has a well-known process for determining the repo URL if one is not given.

https://github.com/munki/munki/wiki/Default-Repo-Detection

**Comment by erikberglund** [comment]
Yeah, I thought about not making that required for another reason when I added that payload, if people wanted to split up the payloads you should not have to include the repo url in every profile.

But I had forgotten about the automatic update, I will fix this now. It should be available as an update from within the application in about an hour.

You update from "Preferences -> Payloads"

**Comment by erikberglund** [comment]
Now it's available for update. I changed the SoftwareRepoURL from being required to being enabled by default, and an admin can disable that key if they want. I did that as I think many people still use that key and it's a core part. Or do you think that the automatic detection should be enough for most people and that I should disable the key by default?

**Comment by erikberglund** [comment]
This has been fixed on the manifest repo.
