### ISSUE TITLE
Export managed preference profiles with content style: MCX does not work.

### ISSUE THREAD

**Issue by erikberglund** [erikberglund/ProfileCreator#62]
Selecting MCX still exports profiles using the profile style.

**Comment by erikberglund** [comment]
I have added a fix for the next release.

**Comment by nathanperkins** [comment]
Is this why JAMF can't seem to see the payload for Munki when I upload?

**Comment by erikberglund** [comment]
With jamf you can either upload a signed profile or it needs to be in the mcx format. Either way should work, if you dont want to sign then it must be in the mcx formar so jamf consideres it a custom payload.

That is a big limitation in JAMF

**Comment by erikberglund** [comment]
Sorry, yes this is why the mcx upload doesnt wotrk

**Comment by erikberglund** [comment]
This was fixed in Beta 6.

**Comment by dvbguy** [comment]
Just an question, without I need to start new issue
If I want to use the created mobileconfig in Jamf how to i do this ? I have tried to import the mobileconfig but it just is empty

**Comment by erikberglund** [comment]
@dvbguy It depends on your profile. Is it an "Apple Payload" profile, meaning it's payloads from Apple defined in the profile specifications, then you should be able to import it as is, but knowing that jamf also might add settings you haven't or don't want to manage for the device. That is why the suggestion always is to sign profiles before uploading them to Jamf.

If it's a third-party payload, i.e. a profile with settings for a third party app or for a general preference domain then you can either choose "XML" as Payload Content Style when exporting the profile. Or you can again, sign the profile and jamf will not be able to modify your settings. 

If you sign the profile you can't edit or see it's contents in the jamf interface, but that is the point as if jamf can read it they apply their own things that might give unintended consequences for you.

So either of those two options are available.
