### ISSUE TITLE
Add payload for SubmitDiagAndUsage skip

### ISSUE THREAD

**Issue by nathanperkins** [erikberglund/ProfileCreator#64]
I tried to import [this profile](https://github.com/rtrouton/profiles/blob/master/SetDiagnosticandUsageReportSettings/SetDiagnosticandUsageReportSettings.mobileconfig) for skipping the Diagnostic and Usage report.

Add Payload Keys currently unavailable in ProfileCreator:
• com.apple.applicationaccess
  - allowDiagnosticSubmission

Payloads currently unavailable in ProfileCreator:
    • com.apple.SubmitDiagInfo

**Comment by erikberglund** [comment]
Both of these are now added to the repository and can be updated from within the app. They will be included in the next release.

If you already have imported these payloads they will not be converted, that will require an application update and I'm unsure if I have time to add that in the next update.

**Comment by erikberglund** [comment]
This was added in Beta 6.
