### ISSUE TITLE
Textfield length is restrictive for certain preferences

### ISSUE THREAD

**Issue by nathanperkins** [erikberglund/ProfileCreator#68]
The textfields can be restrictive when setting fields in certain payloads that can accept a long string like the MessagePasswordChangePolicy in NoMAD.

![screen shot 2018-09-06 at 5 46 20 pm](https://user-images.githubusercontent.com/10337495/45192379-e3693d00-b1fc-11e8-83fb-037ba08394c3.png)

**Comment by erikberglund** [comment]
Did a manual change for this specific key, but the optimal solution is an adaptive textfield but I don't think that will be possible anytime soon. I will look into the focus not following when at the edge of the text field though.

![screen shot 2018-09-08 at 20 41 45](https://user-images.githubusercontent.com/1296345/45257526-c2911b00-b3a7-11e8-8181-e72abd0006d9.png)

**Comment by erikberglund** [comment]
This should be fixed in the latest beta version. Now the text in the text field is scrollable and viewable however long it is.
