### ISSUE TITLE
Microsoft AutoUpdate - 2016 vs. 2019 registering

### ISSUE THREAD

**Issue by kevinmcox** [erikberglund/ProfileCreator#71]
Now that Office 2019 is out, admins will need the ability to specify which version of the applications they want to register with MAU in the profile.

Using Excel as an example:

The current `<key>Application ID</key>` defaults to `<string>XCEL15</string>` which is what admins with 2016 Volume Licenses will want to maintain.

Admins who have O365 users or the 2019 Volume License will need to switch this to `<string>XCEL2019</string>`.

All that changes is the **15** to **2019** in the string.

Since this will be an ongoing thing for a while we'll need the ability for the ProfileCreator user to specify which version they want to register when building the profile.

**Comment by clburlison** [comment]
I disagree. The easier solution is to simply add these new keys. MAU does all the checking so if additional applications are registered it shouldn’t cause any issues. 

This would allow admins to create a single MAU profile for VL2016 & the new 2019 applications. At a later point when all of their fleet is on 2019 they can update the profile to remove all the 2016 keys.

**Comment by erikberglund** [comment]
So, woukd you say that something like this where both could be included at the same time and/or deselected would be the most versatile:

![screen shot 2018-09-14 at 06 17 01](https://user-images.githubusercontent.com/1296345/45529513-ef00c900-b7e5-11e8-80d1-c5dfbf6bad6f.png)

**Comment by erikberglund** [comment]
![screen shot 2018-09-14 at 06 28 04](https://user-images.githubusercontent.com/1296345/45529794-5b2ffc80-b7e7-11e8-98ad-195c4cd698a9.png)

I'm uploading this right now, so that it will be available within 10 minutes for an in app update.

**Comment by kevinmcox** [comment]
Awesome, thanks Erik!

**Comment by erikberglund** [comment]
So, is this format the same for ALL apps in that array?

**Comment by kevinmcox** [comment]
Yes, just replace `15` with `2019` for the Application ID key.

**Comment by erikberglund** [comment]
Right now it looks like this just to get this out there. But I would like to change this format to one setting at the top where you choose the license, and then all fields were populated correctly. But, that will require the thing I talked about eariler. I'll start with this.

Are there any changes for AutoUpdate or Error Reporting, as those didn't have 15 in their ID?

![screen shot 2018-09-14 at 06 34 43](https://user-images.githubusercontent.com/1296345/45529960-75b6a580-b7e8-11e8-88d8-308a828d3fea.png)

**Comment by erikberglund** [comment]
Also, I'll remove the application name from the license selection, that is not necessary.

**Comment by kevinmcox** [comment]
I edited my post above but here is Paul's example application array for Office 2019:

https://github.com/pbowden-msft/Payloads/blob/master/MAU_AppArray2019.plist

**Comment by erikberglund** [comment]
Thanks. I'll add `/Applications/Microsoft Remote Desktop.app` and `/Applications/Company Portal.app` to the list as well then. The AutoUpdate identifier was like before.

**Comment by kevinmcox** [comment]
And of course that is more of an all inclusive Microsoft AutoUpdate array example that includes things that aren't actually part of Office (like Skype, Remote Desktop, etc.) but are updated by MAU.

Which on that note makes me think maybe the MAU profile should be broken out from under Office in ProfileCreator, since in theory there are folks who don't use Office but would still want to create a profile for MAU.

**Comment by kevinmcox** [comment]
And I now I've seen other folks register Error Reporting, but Paul doesn't have it in either of his example payloads.

Here is the original (2016) version: https://github.com/pbowden-msft/Payloads/blob/master/MAU_AppArray.plist

**Comment by kevinmcox** [comment]
OK either I'm crazy and you already had MAU and Office split up and I didn't realize it, or dang you are fast Erik!

**Comment by erikberglund** [comment]
Thanks. I have updated the payload and it's available to update now. 

It was @clburlison who did this payload and I believe it was always called Microsoft AutoUpdate, so forward thinking on his part :)

**Comment by erikberglund** [comment]
I am planning on adding the other office-payloads within a few days. And should look at the updates, there were new keys I beliave.

**Comment by clburlison** [comment]
This looks perfect Erik! I’m sure it’s gonna look even better in the future with the change you’re talking about but functionally this does what everyone will be needing for the near future.
