### ISSUE TITLE
Mark payloads/fields with minimum OS version?

### ISSUE THREAD

**Issue by nathanperkins** [erikberglund/ProfileCreator#72]
Maybe this has already been suggested but what would your thoughts be on being able to add the minimum OS version to payloads and fields? That might be helpful as new features are added to profiles which might not work on older OSes.

**Comment by erikberglund** [comment]
Yes, this is planned and the values where that information is available is already set in the existing manifests. Example: https://github.com/erikberglund/ProfileManifests/blob/175cd64104c891a54ebfe7fbe2007a3654e3546b/Manifests/ManifestsApple/com.apple.wifi.managed.plist#L184-L187

So it's only the representation in the app that's not implemented. And that is definitely planned.

**Comment by mikedowler** [comment]
Could we add maximum OS versions as well?  We should keep older settings for people who need to support them, but having the data there would allow them to be filtered out if desired.

**Comment by apizz** [comment]
Not sure when this was specifically implemented, but you can definitely add this to individual preferences and the entire payload within a manifest using any of the following:
[`pfm_ios_min`](https://github.com/erikberglund/ProfileManifests/wiki/Manifest-Format)
[`pfm_ios_max`](https://github.com/erikberglund/ProfileManifests/wiki/Manifest-Format)
[`pfm_macos_min`](https://github.com/erikberglund/ProfileManifests/wiki/Manifest-Format)
[`pfm_macos_max`](https://github.com/erikberglund/ProfileManifests/wiki/Manifest-Format)
[`pmf_tvos_min`](https://github.com/erikberglund/ProfileManifests/wiki/Manifest-Format)
[`pfm_tvos_max`](https://github.com/erikberglund/ProfileManifests/wiki/Manifest-Format)

These will be visible in the GUI in 0.2.5
