### ISSUE TITLE
Feature Request: Custom Keys

### ISSUE THREAD

**Issue by ahrenstein** [erikberglund/ProfileCreator#74]
I noticed that the ScreenSaver policy only sets loginWindowIdleTime but I also wanted to set idleTime so that end users have a screen saver timeout. I could not find an option for it, nor could I find a way to manually edit the profile in Profile Creator.

It'd be really nice to have a section to deploy a custom payload. Maybe something as simple as allowing you to add key:value pairs or even just a place to edit raw XML and have it lint it before letting you save it.

**Comment by erikberglund** [comment]
Yes absolutely on both, this is a very needed feature, both Entirely custom and to add single keys. It is planned and coming.

Regarding the screensaver, that is a tricky payload. It exists in 3 domains and with different settings. I can respond better tomorrow about that specific payload.

**Comment by ahrenstein** [comment]
Yeah I figured that. The idleTime key does work in a computer scoped policy though, so I manually edited the profile in an IDE before signing it and uploading it to Jamf. Good tip though to know I can find the keys this way.

Thanks

**Comment by erikberglund** [comment]
Ah, great. Then I'll add `idleTime` to the computer scope as well. I have added a new key to the manifest to describe the documentation source for each key, and in this case it will be empty as the documentation doesn't include this. In the future that information will be included in the app somewhere so one can easier check the documentation of a key.

**Comment by erikberglund** [comment]
By the way did you try the `loginWindowIdleTime` key for the computer level? It has the exact same description as the idleTime but at the computer level.

**Comment by ahrenstein** [comment]
Awesome! Thanks.

**Comment by apizz** [comment]
@ahrenstein is this issue resolved?  If so, please close this issue.

**Comment by ahrenstein** [comment]
Oh yeah this is resolved.

Thanks a ton
