### ISSUE TITLE
System Preference Panes clarification and/or feature request

### ISSUE THREAD

**Issue by roodavis** [erikberglund/ProfileCreator#76]
I'm trying to understand if there is a difference or purpose in the "Enabled Preference Panes" and "Disabled Preference Panes" selection in the com.apple.systempreferences payload panel in ProfileCreator. It appears that the result would be the same when using one or the other.

I think that the Disabled Preference Pane should be changed to use the HiddenPreferencePanes key. These two screenshots show the difference.

**With DisabledPreferencePanes key/array, but HiddenPreferencePanes key/array NOT used**
![sysprefs_withouthiddenkey](https://user-images.githubusercontent.com/18036516/46583840-77ac0700-ca2a-11e8-820b-f258de68a01c.png)

**With DisabledPreferencePanes key/array and HiddenPreferencePanes key/array**
![sysprefs_withhiddenkey](https://user-images.githubusercontent.com/18036516/46583841-77ac0700-ca2a-11e8-9440-bbc0692ae0dc.png)

**Comment by erikberglund** [comment]
I'm sorry. I misunderstood when I first read this issues.

It seems that the Hidden key is missing, I will add that, as they are doing different things. Thanks. I'll add and update later today

**Comment by erikberglund** [comment]
I've added that updated manifest to the repo, so you can update and use the hidden setting now.
