### ISSUE TITLE
missing keys for FileVault 

### ISSUE THREAD

**Issue by fauxserve** [erikberglund/ProfileCreator#79]
I've got a (modified) profile that started out in Jamf. We are modifying the code to suit our needs, but I ran across these errors when I tried to import it. 

Thank you for all your amazing work! This is a fantastic tool.

*************

Payloads currently unavailable in ProfileCreator:

    • com.apple.systempolicy.managed
    • com.apple.security.FDERecoveryKeyEscrow

The contents of the unavailable payloads can still be viewed and exported but not edited by ProfileCreator.

Payload Keys currently unavailable in ProfileCreator:

• com.apple.MCX
  - dontAllowFDEDisable
  - DestroyFVKeyOnStandby

**Comment by erikberglund** [comment]
Thanks for the report, correct not all manifest and keys are included. I will add these to the next release which is due in 1-2 days probably.

**Comment by erikberglund** [comment]
The missing payloads are added in the new release of the app. The MCX-keys are not added yet as I will have to resolve an issue where a payload have multiple functions, like the mcx-payload. Currently there is no good way of separating those in logical units. That will require code changes and that is not included in this update unfortunately.

**Comment by erikberglund** [comment]
This will finally be fixed in the next release.

**Comment by apizz** [comment]
Fixed in 0.2.5 release
