### ISSUE TITLE
Can't add additional array items without removing and readding the preference

### ISSUE THREAD

**Issue by apizz** [erikberglund/ProfileCreator#84]
I've tried doing this via several different manifests and payloads that have an array of strings or array of integers, but the results are the same.

When you click the + button to add the first item in an array, the entry field appears fine and you can type your desired value.  However, clicking the + button again to add another item to the array doesn't actually create another field.  It reselects the previously added value.

However, when you enter your value, click the X to remove the payload, and then click the + to add the payload again, when you then press the + button to add an additional array item it correctly adds another item field.  This temporary removal and readding of the payload is necessary to get additional fields to be added.  I confirmed this on both the GUI side and the XML view side.

**Comment by erikberglund** [comment]
Thanks for this report and yes that is a bug, but its fixed in my dev build so it will be fixed on next version.

**Comment by apizz** [comment]
Resolved in latest beta
