### ISSUE TITLE
Add support for 'real' keys & values

### ISSUE THREAD

**Issue by apizz** [erikberglund/ProfileCreator#86]
In both of the manifests I've been working on - AirServer & DetectX Swift - both use `real` number keys (`<real></real>`) in some capacity.

However, it appears that when real numbers are used as part of a preference in a manifest, the preference doesn't appear at all.  Here is an example:

```
                  <dict>
			<key>pfm_name</key>
			<string>SUScheduledCheckInterval</string>
			<key>pfm_type</key>
			<string>real</string>
			<key>pfm_description</key>
			<string>Frequency to complete automatic software update checks.</string>
			<key>pfm_range_list</key>
			<array>
				<real>3600</real>
				<real>86400</real>
				<real>604800</real>
				<real>2629800</real>
			</array>
			<key>pfm_range_list_titles</key>
			<array>
				<string>Hourly</string>
				<string>Daily</string>
				<string>Weekly</string>
				<string>Monthly</string>
			</array>
		</dict>
```

**Comment by erikberglund** [comment]
That is currently only set when using `float`, but good idea, is should add real as an alias too.

**Comment by erikberglund** [comment]
I've added this to the next update. You can then use both `real` or `float` for the floating point numbers.
