### ISSUE TITLE
Preference text fields larger than 1 line cover exclusion messages

### ISSUE THREAD

**Issue by apizz** [erikberglund/ProfileCreator#87]
Recently discovered the `pfm_range_max` key for increasing the size of the text field for strings.

It appears that this larger text field covers any configured exclusion rules.  You can just make out the text at the bottom of the image.

![screen shot 2018-11-28 at 12 20 55 am](https://user-images.githubusercontent.com/11789931/49130790-9b116680-f2a3-11e8-8685-c38154fcf4fc.png)

**Comment by erikberglund** [comment]
Good catch, willd add a fix

**Comment by erikberglund** [comment]
Fixed this for the next update. 
![screenshot 2018-12-03 at 11 12 08](https://user-images.githubusercontent.com/1296345/49367414-4e3aef00-f6ec-11e8-9572-2b134ea8ba84.png)
