### ISSUE TITLE
Inconsistent Visual "Disabled Keys" Message in Manifests

### ISSUE THREAD

**Issue by apizz** [erikberglund/ProfileCreator#90]
When I wrote my first manifests, I noticed that neither DetectX nor AirServer had the "Disabled Keys" message line at the top to visually separate disabled preference keys between those that are added that I was seeing in other preferences.

I'm trying to figure out why this is, and have noticed a couple of patterns.

1. Manifests with a default enabled / required preference don't appear to show this message.
  
![screen shot 2018-12-07 at 3 07 04 pm](https://user-images.githubusercontent.com/11789931/49670198-dba27a00-fa31-11e8-9b84-1dae14c12536.png)
![screen shot 2018-12-07 at 3 07 15 pm](https://user-images.githubusercontent.com/11789931/49670203-e0672e00-fa31-11e8-9bbe-a7312dcbe7dd.png)

2. Manifests with the horizontal toggle menus to organize preference keys at the very top also don't show this message.  This may be the more accurate root cause, since the two images above have these menus immediately following the auto-added preferences, but Sal below does not.

![screen shot 2018-12-07 at 3 15 21 pm](https://user-images.githubusercontent.com/11789931/49670510-f0334200-fa32-11e8-9a1c-7c7b09597160.png)
![screen shot 2018-12-07 at 3 32 48 pm](https://user-images.githubusercontent.com/11789931/49671315-75b7f180-fa35-11e8-98bc-256fd6f0bec2.png)

3. Those manifests without these consistently have the Disabled message

![screen shot 2018-12-07 at 3 26 35 pm](https://user-images.githubusercontent.com/11789931/49671019-80be5200-fa34-11e8-9ed9-1929873fd9a7.png)
![screen shot 2018-12-07 at 3 26 58 pm](https://user-images.githubusercontent.com/11789931/49671028-8f0c6e00-fa34-11e8-99a9-9f95e5efed5e.png)

Hoping to get this fixed for those apps that organize preferences in this way, so it's clearer what's enabled and what's not enabled in the payload.

**Comment by erikberglund** [comment]
That is by design, if you have a segmented control it would be confusing if the settings would be shown outside the selected control title and it would be hard to Find other settings that might go with it.

There is an option to not show segmented controls then you will have all keys in a Long row with the disabled message.

**Comment by apizz** [comment]
Ahh that makes a lot of sense.  In that case, nothing to be done here.
