### ISSUE TITLE
Corrupted download?

### ISSUE THREAD

**Issue by wjk** [erikberglund/ProfileCreator#93]
I am trying to download and install ProfileCreator 0.2.3 (beta 8) on my MacBook Pro. I downloaded the dmg file three times, and each time the file refuses to open, telling me "no mountable file systems". It's been a while since I last installed ProfileCreator, but if I recall correctly this release worked fine in the past. My system details are below. Thanks for looking into this for me!

* macOS Mojave, version 10.14.1
* Model: MacBook Pro, 15-inch, 2018 (MacBookPro15,1)

**Comment by erikberglund** [comment]
Hey, yeah 2 more people have Said the same thing. I think its because the dmg is signed but its weird that it works for most people. Im about to put up a bugfix version today and ill add several different download links  as backup

**Comment by wjk** [comment]
I have confirmed that the beta 9 DMG opens and mounts correctly. Thanks for your help!
