### ISSUE TITLE
Please add ability to copy text in payload descriptions

### ISSUE THREAD

**Issue by bp88** [erikberglund/ProfileCreator#94]
Currently you cannot select/highlight text that shows up in the profile payload descriptions for the individual values. This would allow one to copy/paste relevant information from the app without having to go directly into the Profile Manifests.

**Comment by erikberglund** [comment]
Thanks for noticing this, I assume more people will want this so have changed that now for the next update.

**Comment by erikberglund** [comment]
This was fixed.
