### ISSUE TITLE
How to use Login Scripts

### ISSUE THREAD

**Issue by jekastner** [erikberglund/ProfileCreator#98]
Hi Erik, 

Getting better at using Profile Creator! We in my Dept love it. I need some help understanding how to use Login Window: Scripts. I have a executable Shell Script but when I add my to the Script to run at login. AND I try to export this Profile I get this message. What am I doing wrong?

![screen shot 2018-12-18 at 10 08 31 am](https://user-images.githubusercontent.com/43783356/50178325-d06d0b00-02c9-11e9-9750-0d38d586b827.png)

**Comment by erikberglund** [comment]
This might be the bug i found with bp, I will test tomorrow and upload a custom build here to see if it fixes this issue. You are probably not doing anything wrong in this case.

**Comment by erikberglund** [comment]
Hi, could you try this build. You will have to re-add the information in the login scripts payload to have it save correctly. 
[ProfileCreator.app.zip](https://github.com/erikberglund/ProfileCreator/files/2698522/ProfileCreator.app.zip)

**Comment by apizz** [comment]
@jekastner is this still an issue, or has this been resolved?

**Comment by jekastner** [comment]
@apizz This seems to be resolved.
